### ISSUE TITLE
data transmission!!!!!!

### ISSUE THREAD

**Issue by Carex-Chunhui** [mc2-project/federated-xgboost#22]
The update data transfer interface here is encapsulated in the libxgboost.so file, but I want to compress it to reduce the bandwidth. Can you provide the source code of libxgboost.so? Or provide a compression interface for data transmission externally.

**Comment by Carex-Chunhui** [comment]
I noticed mbedtls_ net_ Recv and mbedtls_ net_ send in the libxgboost.so file，  but how to do？

**Comment by chester-leung** [comment]
Hi @Carex-Chunhui , the code in the [`src`](https://github.com/mc2-project/federated-xgboost/tree/master/src) directory gets built into `libxgboost.so`. Much of the networking is done in Rabit, which is a submodule of Federated XGBoost. You can take a look at [this PR](https://github.com/mc2-project/rabit/commit/286183c82d4ebdc3e0ea5319e5d16bd097dd55e3) to see how we integrated Mbed TLS into Rabit.

**Comment by Carex-Chunhui** [comment]
thank you very much~
